// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using PaxosCLI;
using PaxosCLI.Database;

namespace PaxosCLI.Migrations;

[DbContext(typeof(Ledger))]
partial class LedgerModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

        modelBuilder.Entity("PaxosCLI.LedgerEntry", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Decree");

                b.HasKey("Id");

                b.ToTable("Entries");
            });

        modelBuilder.Entity("PaxosCLI.PaxosProgress", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<decimal>("LastTried");

                b.Property<decimal>("NextBal");

                b.Property<decimal>("PrevBal");

                b.Property<byte[]>("PrevDec");

                b.HasKey("Id");

                b.ToTable("Progress");

                b.HasData(
                    new { Id = 1, LastTried = -79228162514264337593543950335m, NextBal = -79228162514264337593543950335m, PrevBal = -79228162514264337593543950335m, PrevDec = new byte[] {  } }
                );
            });
#pragma warning restore 612, 618
    }
}

